package com.junior;
// Generated 18/jan/2019 22:29:22 by Hibernate Tools 4.3.1

/**
 * Pagamento generated by hbm2java
 */
public class Pagamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PagamentoId id;

	public Pagamento() {
	}

	public Pagamento(PagamentoId id) {
		this.id = id;
	}

	public PagamentoId getId() {
		return this.id;
	}

	public void setId(PagamentoId id) {
		this.id = id;
	}

	@Override
	public String toString() {
		return "Pagamento [id=" + id + "]";
	}
	
	

}
